In [1]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
from sklearn import datasets
file = "../data/dexcomData.csv"

In [4]:
glucose = pd.read_csv(file)

In [5]:
glucose.head()

   Blood Glucose (mg/dL)  Rate (mg/dL/min)            Timestamp
0                  206.0               0.4  2018-10-27 21:27:07
1                  205.0               0.3  2018-10-27 21:22:07
2                  203.0               0.1  2018-10-27 21:17:07
3                  202.0               0.1  2018-10-27 21:12:07
4                  202.0               0.1  2018-10-27 21:07:07

In [6]:
glucose.sort_values('Timestamp')

       Blood Glucose (mg/dL)  Rate (mg/dL/min)            Timestamp
73525                   72.0               0.8  2017-09-11 22:22:07
73524                   78.0               1.2  2017-09-11 22:26:59
73523                   69.0               0.6  2017-09-11 22:31:59
73522                   70.0              12.7  2017-09-11 22:36:58
73521                   61.0              12.7  2017-09-11 22:41:59
73520                   39.0              -2.1  2017-09-11 22:46:59
73519                   39.0              -2.2  2017-09-11 22:51:59
73518                   39.0              -2.1  2017-09-11 22:56:58
73517                   39.0              -0.8  2017-09-11 23:01:59
73516                   39.0              -1.0  2017-09-11 23:06:59
73515                   39.0              -0.8  2017-09-11 23:11:59
73514                   39.0              12.7  2017-09-11 23:16:58
73513                   39.0              12.7  2017-09-11 23:21:59
73512                   48.0              12.7  2017-09-11 23:26:59
73511                   77.0              12.7  2017-09-11 23:41:59
73510                   80.0              12.7  2017-09-11 23:46:58
73509                   74.0              12.7  2017-09-11 23:51:58
73508                   73.0              12.7  2017-09-11 23:56:59
73507                   62.0              12.7  2017-09-12 00:01:59
73506                   58.0              12.7  2017-09-12 00:06:58
73505                   55.0              -1.0  2017-09-12 00:11:58
73504                   54.0              -0.7  2017-09-12 00:16:57
73503                   51.0              -0.5  2017-09-12 00:21:58
73502                   47.0              -0.5  2017-09-12 00:26:58
73501                   43.0              -0.7  2017-09-12 00:31:57
73500                   39.0              -0.8  2017-09-12 00:36:58
73499                   39.0              -0.6  2017-09-12 00:41:58
73498                   40.0              -0.2  2017-09-12 00:46:57
73497                   42.0               0.1  2017-09-12 00:51:58
73496                   70.0               0.5  2017-09-12 00:57:04
...                      ...               ...                  ...
29                     165.0              -0.5  2018-10-27 19:02:07
28                     161.0              -0.9  2018-10-27 19:07:07
27                     156.0              -1.0  2018-10-27 19:12:07
26                     159.0              -0.5  2018-10-27 19:17:07
25                     163.0               0.1  2018-10-27 19:22:08
24                     160.0               0.1  2018-10-27 19:27:07
23                     160.0               0.1  2018-10-27 19:32:07
22                     160.0              -0.1  2018-10-27 19:37:06
21                     163.0               0.2  2018-10-27 19:42:07
20                     164.0               0.4  2018-10-27 19:47:07
19                     167.0               0.6  2018-10-27 19:52:07
18                     169.0               0.6  2018-10-27 19:57:07
17                     176.0               0.9  2018-10-27 20:02:07
16                     179.0               1.0  2018-10-27 20:07:07
15                     186.0               1.3  2018-10-27 20:12:07
14                     180.0               0.4  2018-10-27 20:17:07
13                     189.0               0.8  2018-10-27 20:22:07
12                     188.0               0.5  2018-10-27 20:27:07
11                     190.0               0.6  2018-10-27 20:32:07
10                     194.0               0.7  2018-10-27 20:37:07
9                      196.0               0.6  2018-10-27 20:42:07
8                      199.0               0.7  2018-10-27 20:47:07
7                      200.0               0.5  2018-10-27 20:52:07
6                      201.0               0.4  2018-10-27 20:57:07
5                      202.0               0.3  2018-10-27 21:02:07
4                      202.0               0.1  2018-10-27 21:07:07
3                      202.0               0.1  2018-10-27 21:12:07
2                      203.0               0.1  2018-10-27 21:17:07
1                      205.0               0.3  2018-10-27 21:22:07
0                      206.0               0.4  2018-10-27 21:27:07

[73526 rows x 3 columns]

In [7]:
glucose['Timestamp'] = pd.to_datetime(glucose['Timestamp'])

In [8]:
glucose.set_index('Timestamp')

                     Blood Glucose (mg/dL)  Rate (mg/dL/min)
Timestamp
2018-10-27 21:27:07                  206.0               0.4
2018-10-27 21:22:07                  205.0               0.3
2018-10-27 21:17:07                  203.0               0.1
2018-10-27 21:12:07                  202.0               0.1
2018-10-27 21:07:07                  202.0               0.1
2018-10-27 21:02:07                  202.0               0.3
2018-10-27 20:57:07                  201.0               0.4
2018-10-27 20:52:07                  200.0               0.5
2018-10-27 20:47:07                  199.0               0.7
2018-10-27 20:42:07                  196.0               0.6
2018-10-27 20:37:07                  194.0               0.7
2018-10-27 20:32:07                  190.0               0.6
2018-10-27 20:27:07                  188.0               0.5
2018-10-27 20:22:07                  189.0               0.8
2018-10-27 20:17:07                  180.0               0.4
2018-10-27 20:12:07                  186.0               1.3
2018-10-27 20:07:07                  179.0               1.0
2018-10-27 20:02:07                  176.0               0.9
2018-10-27 19:57:07                  169.0               0.6
2018-10-27 19:52:07                  167.0               0.6
2018-10-27 19:47:07                  164.0               0.4
2018-10-27 19:42:07                  163.0               0.2
2018-10-27 19:37:06                  160.0              -0.1
2018-10-27 19:32:07                  160.0               0.1
2018-10-27 19:27:07                  160.0               0.1
2018-10-27 19:22:08                  163.0               0.1
2018-10-27 19:17:07                  159.0              -0.5
2018-10-27 19:12:07                  156.0              -1.0
2018-10-27 19:07:07                  161.0              -0.9
2018-10-27 19:02:07                  165.0              -0.5
...                                    ...               ...
2017-09-12 00:57:04                   70.0               0.5
2017-09-12 00:51:58                   42.0               0.1
2017-09-12 00:46:57                   40.0              -0.2
2017-09-12 00:41:58                   39.0              -0.6
2017-09-12 00:36:58                   39.0              -0.8
2017-09-12 00:31:57                   43.0              -0.7
2017-09-12 00:26:58                   47.0              -0.5
2017-09-12 00:21:58                   51.0              -0.5
2017-09-12 00:16:57                   54.0              -0.7
2017-09-12 00:11:58                   55.0              -1.0
2017-09-12 00:06:58                   58.0              12.7
2017-09-12 00:01:59                   62.0              12.7
2017-09-11 23:56:59                   73.0              12.7
2017-09-11 23:51:58                   74.0              12.7
2017-09-11 23:46:58                   80.0              12.7
2017-09-11 23:41:59                   77.0              12.7
2017-09-11 23:26:59                   48.0              12.7
2017-09-11 23:21:59                   39.0              12.7
2017-09-11 23:16:58                   39.0              12.7
2017-09-11 23:11:59                   39.0              -0.8
2017-09-11 23:06:59                   39.0              -1.0
2017-09-11 23:01:59                   39.0              -0.8
2017-09-11 22:56:58                   39.0              -2.1
2017-09-11 22:51:59                   39.0              -2.2
2017-09-11 22:46:59                   39.0              -2.1
2017-09-11 22:41:59                   61.0              12.7
2017-09-11 22:36:58                   70.0              12.7
2017-09-11 22:31:59                   69.0               0.6
2017-09-11 22:26:59                   78.0               1.2
2017-09-11 22:22:07                   72.0               0.8

[73526 rows x 2 columns]

In [9]:
x = glucose.drop('Rate (mg/dL/min)', axis = 1)

In [10]:
y = glucose['Blood Glucose (mg/dL)']

In [11]:
x.head()
type(x['Timestamp'][0])

   Blood Glucose (mg/dL)           Timestamp
0                  206.0 2018-10-27 21:27:07
1                  205.0 2018-10-27 21:22:07
2                  203.0 2018-10-27 21:17:07
3                  202.0 2018-10-27 21:12:07
4                  202.0 2018-10-27 21:07:07

pandas._libs.tslibs.timestamps.Timestamp

In [13]:
x['Timestamp'] = x['Timestamp'].dt.strftime('%Y%m%d').astype(float).head()
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.3, random_state=1)
train_x.shape
test_x.shape
train_y.shape
test_y.shape

(51468, 2)

(22058, 2)

(51468,)

(22058,)

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet

In [15]:
lm = LinearRegression()

In [16]:
lm_lasso = Lasso()

In [17]:
lm_ridge = Ridge()

In [18]:
lm_elastic = ElasticNet()

In [19]:
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [20]:
lm_lasso

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [21]:
lm_ridge

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [22]:
lm_elastic

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [23]:
lm.fit(train_x, train_y)
lm_lasso.fit(train_x, train_y)
lm_ridge.fit(train_x, train_y)
lm_elastic.fit(train_x, train_y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
plt.figure(figsize=(15,10))
ft_importances_lm = pd.Series(lm.coef_, index= x.columns)
ft_importances_lm.plot(kind='line')
plt.show()